import Foundation
import VaultCore

/// A `VaultItem` retrieved from storage.
///
/// Includes the unique ID used to identify this item.
public struct StoredVaultItem: Equatable, Hashable, Identifiable {
    public var id: UUID
    public var created: Date
    public var updated: Date
    public var userDescription: String?
    /// The stored vault item.
    public var item: VaultItem

    public init(id: UUID, created: Date, updated: Date, userDescription: String?, item: VaultItem) {
        self.id = id
        self.created = created
        self.updated = updated
        self.userDescription = userDescription
        self.item = item
    }

    /// Maps this object to a `StoredVaultItem.Write` for writing.
    public var asWritable: StoredVaultItem.Write {
        .init(userDescription: userDescription, item: item)
    }
}

public extension StoredVaultItem {
    struct Metadata: Equatable, Hashable, Identifiable {
        /// A unique ID to identify this specific `item`.
        ///
        /// This should be generated by the storage layer.
        public var id: UUID
        public var created: Date
        public var updated: Date
        /// User-provided description about the item.
        public var userDescription: String?

        public init(id: UUID, created: Date, updated: Date, userDescription: String?) {
            self.id = id
            self.created = created
            self.updated = updated
            self.userDescription = userDescription
        }
    }
}

public extension StoredVaultItem {
    /// Model used for creating or updating a new `VaultItem`, where the `id` is predetermined/generated randomly.
    struct Write: Equatable {
        public var userDescription: String?
        public var item: VaultItem

        public init(userDescription: String? = nil, item: VaultItem) {
            self.userDescription = userDescription
            self.item = item
        }
    }
}
