import CryptoEngine
import Foundation
import FoundationExtensions
import VaultCore

/// A `VaultItem` retrieved from storage.
///
/// Includes the unique ID used to identify this item.
public struct VaultItem: Equatable, Hashable, Identifiable, Sendable {
    /// An item of data that can be stored in the Vault.
    public enum Payload: Equatable, Hashable, Sendable {
        case otpCode(OTPAuthCode)
        case secureNote(SecureNote)
        case encryptedItem(EncryptedItem)
    }

    /// Information about the stored item.
    public var metadata: Metadata
    /// The stored vault item.
    public var item: Payload

    public init(metadata: Metadata, item: Payload) {
        self.metadata = metadata
        self.item = item
    }

    public var id: Identifier<VaultItem> {
        metadata.id
    }

    /// Maps this object to a `VaultItem.Write` for writing.
    ///
    /// This discards any non-deterministic data and identifiable information.
    public func makeWritable() -> VaultItem.Write {
        .init(
            relativeOrder: metadata.relativeOrder,
            userDescription: metadata.userDescription,
            color: metadata.color,
            item: item,
            tags: metadata.tags,
            visibility: metadata.visibility,
            searchableLevel: metadata.searchableLevel,
            searchPassphrase: metadata.searchPassphrase,
            killphraseUpdate: metadata.killphrase.map { .set($0) } ?? .clear,
            lockState: metadata.lockState,
            showInQuickType: metadata.showInQuickType,
            previewMode: metadata.previewMode,
        )
    }

    /// Create a context when importing this data.
    public func makeImportingContext() -> VaultItem.WriteUpdateContext {
        .init(id: id, created: metadata.created, updated: .retainUpdatedDate(metadata.updated))
    }

    /// Checks if all deterministic content in a given vault item is equal to an `other` item.
    ///
    /// This ignores data that is not user-determined.
    /// For example, the created and updated date.
    func isContentEqual(to other: VaultItem) -> Bool {
        // The 'writable' content is all deterministic
        makeWritable() == other.makeWritable() &&
            id == other.id
    }
}

extension VaultItem: Digestable {
    public var digestableData: some Encodable {
        struct Container: Encodable {
            var id: UUID
            var updatedDate: Date
        }
        return Container(id: metadata.id.rawValue, updatedDate: metadata.updated)
    }
}

extension VaultItem.Payload {
    public var otpCode: OTPAuthCode? {
        switch self {
        case let .otpCode(otpCode):
            otpCode
        default:
            nil
        }
    }

    public var secureNote: SecureNote? {
        switch self {
        case let .secureNote(note):
            note
        default:
            nil
        }
    }

    public var encryptedItem: EncryptedItem? {
        switch self {
        case let .encryptedItem(data): data
        default: nil
        }
    }
}

extension VaultItem {
    /// Common metadata for all stored vault items.
    public struct Metadata: Equatable, Hashable, Identifiable, Sendable {
        /// A unique ID to identify this specific `item`.
        ///
        /// This should be generated by the storage layer.
        public let id: Identifier<VaultItem>
        public let created: Date
        public var updated: Date
        public var relativeOrder: UInt64
        /// User-provided description about the item.
        public var userDescription: String
        public var visibility: VaultItemVisibility
        public var searchableLevel: VaultItemSearchableLevel
        public var tags: Set<Identifier<VaultItemTag>>
        public var searchPassphrase: String?
        /// One-way digest representing the phrase that, when entered, will
        /// immediately delete this item. `nil` when no killphrase is set.
        /// The plaintext phrase is never persisted or surfaced through the
        /// model.
        public var killphrase: KillphraseDigest?
        /// Whether this item has a killphrase set.
        public var killphraseEnabled: Bool {
            killphrase != nil
        }

        public var lockState: VaultItemLockState
        /// The color tint for this item.
        public var color: VaultItemColor?
        /// Whether this item should appear in QuickType suggestions.
        public var showInQuickType: Bool
        /// Controls what appears in the at-a-glance preview tile (note items only).
        public var previewMode: NotePreviewMode

        public init(
            id: Identifier<VaultItem>,
            created: Date,
            updated: Date,
            relativeOrder: UInt64,
            userDescription: String,
            tags: Set<Identifier<VaultItemTag>>,
            visibility: VaultItemVisibility,
            searchableLevel: VaultItemSearchableLevel,
            searchPassphrase: String?,
            killphrase: KillphraseDigest?,
            lockState: VaultItemLockState,
            color: VaultItemColor?,
            showInQuickType: Bool,
            previewMode: NotePreviewMode,
        ) {
            self.id = id
            self.created = created
            self.updated = updated
            self.relativeOrder = relativeOrder
            self.userDescription = userDescription
            self.tags = tags
            self.visibility = visibility
            self.searchableLevel = searchableLevel
            self.searchPassphrase = searchPassphrase
            self.killphrase = killphrase
            self.lockState = lockState
            self.color = color
            self.showInQuickType = showInQuickType
            self.previewMode = previewMode
        }
    }
}

extension VaultItem {
    /// How the killphrase field should be modified on write.
    public enum KillphraseUpdate: Equatable, Sendable {
        /// Keep whatever is already persisted (no-op on update; equivalent
        /// to `.clear` for a brand-new insert that has no existing value).
        case unchanged
        /// Remove any existing killphrase.
        case clear
        /// Replace the killphrase with the provided digest.
        case set(KillphraseDigest)
    }

    /// Model used for creating or updating a new `VaultItem`, where the `id` is predetermined/generated randomly.
    public struct Write: Equatable, Sendable {
        public var relativeOrder: UInt64
        public var userDescription: String
        public var color: VaultItemColor?
        public var item: Payload
        public var tags: Set<Identifier<VaultItemTag>>
        public var visibility: VaultItemVisibility
        public var searchableLevel: VaultItemSearchableLevel
        public var searchPassphrase: String?
        public var killphraseUpdate: KillphraseUpdate
        public var lockState: VaultItemLockState
        public var showInQuickType: Bool
        public var previewMode: NotePreviewMode

        public init(
            relativeOrder: UInt64,
            userDescription: String,
            color: VaultItemColor?,
            item: Payload,
            tags: Set<Identifier<VaultItemTag>>,
            visibility: VaultItemVisibility,
            searchableLevel: VaultItemSearchableLevel,
            searchPassphrase: String?,
            killphraseUpdate: KillphraseUpdate,
            lockState: VaultItemLockState,
            showInQuickType: Bool,
            previewMode: NotePreviewMode,
        ) {
            self.relativeOrder = relativeOrder
            self.userDescription = userDescription
            self.color = color
            self.item = item
            self.tags = tags
            self.visibility = visibility
            self.searchableLevel = searchableLevel
            self.searchPassphrase = searchPassphrase
            self.killphraseUpdate = killphraseUpdate
            self.lockState = lockState
            self.showInQuickType = showInQuickType
            self.previewMode = previewMode
        }
    }

    /// Writable data used when importing or updating, we we have known values for these
    /// existing fields.
    public struct WriteUpdateContext: Sendable {
        public var id: Identifier<VaultItem>
        public var created: Date
        public var updated: UpdateContext

        public init(id: Identifier<VaultItem>, created: Date, updated: UpdateContext) {
            self.id = id
            self.created = created
            self.updated = updated
        }
    }
}
