# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

desc "Increments the build number and commits this change"
lane :increment_build do
  ensure_git_status_clean
  increment_build_number
  commit_version_bump(
    force: true
  )
end

platform :ios do
  desc "Push a new release build to the App Store"


  lane :release do
    get_certificates
    get_provisioning_profile(app_identifier: "com.badbundle.vault")
    get_provisioning_profile(app_identifier: "com.badbundle.vault.VaultAppAutofill")
    increment_build
    build_app(
      workspace: "Vault.xcworkspace",
      scheme: "VaultApp",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.badbundle.vault" => "vault.mobileprovision",
          "com.badbundle.vault.VaultAppAutofill" => "vault-autofill.mobileprovision"
        }
      },
      clean: true
    )
    upload_to_app_store
  end
end
