indentation: 4

excluded:
  - .build

opt_in_rules:
  - fatal_error_message
  - implicitly_unwrapped_optional
  - operator_usage_whitespace
  - unowned_variable_capture
  - no_coreData
  - no_objcMembers
  - no_nsLocalizedString
  - no_NSRegularExpression
  - no_direct_standard_out_logs
  - no_unchecked_sendable
  - no_preconcurrency
  - no_xctest

# Some are dumb, some are broken.
# Broken ones are commented.
disabled_rules:
  - identifier_name
  - nesting
  - trailing_comma
  - line_length
  - large_tuple
  - type_name
  - type_body_length
  - file_length
  - todo
  - function_body_length
  - cyclomatic_complexity
  - blanket_disable_command
  - opening_brace # incompat with swiftformat
  - closure_parameter_position # incompat with swiftformat
  - void_function_in_ternary # broken, sees inits as void functions

colon:
  apply_to_dictionaries: false

custom_rules:
  no_coreData:
    name: "No CoreData"
    regex: "(\\bNSManagedObject|\\bNSManagedObjectContext|\\bNSPersistentContainer\\bNSManagedObjectModel)"
    message: "Prefer SwiftData to CoreData"
    severity: error
  no_objcMembers:
    name: "@objcMembers"
    regex: "@objcMembers"
    message: "Explicitly use @objc on each member you want to expose to Objective-C"
    severity: error
  no_nsLocalizedString:
    name: "NSLocalizedString"
    regex: "NSLocalizedString"
    message: "Use String.LocalizationValue"
    severity: error
  no_NSRegularExpression:
    name: "NSRegularExpression"
    regex: "NSRegularExpression"
    message: "Use String.Regex"
    severity: error
  no_direct_standard_out_logs:
    name: "Writing log messages directly to standard out is disallowed"
    regex: "(\\bprint|\\bdebugPrint|\\bdump|Swift\\.print|Swift\\.debugPrint|Swift\\.dump)\\s*\\("
    match_kinds:
      - identifier
    message: "Don't commit `print(…)`, `debugPrint(…)`, or `dump(…)` as they write to standard out in release. Either log to a dedicated logging system or silence this warning in debug-only scenarios explicitly using `// swiftlint:disable:next no_direct_standard_out_logs`"
    severity: warning
  no_unchecked_sendable:
    name: "`@unchecked Sendable` is discouraged."
    regex: "@unchecked Sendable"
    match_kinds:
      - attribute.builtin
      - typeidentifier
    message: "Instead of using `@unchecked Sendable`, consider a safe alternative like a standard `Sendable` conformance or using `@preconcurrency import`. If you really must use `@unchecked Sendable`, you can add a `// swiftlint:disable:next no_unchecked_sendable` annotation with an explanation for how we know the type is thread-safe, and why we have to use @unchecked Sendable instead of Sendable. More explanation and suggested safe alternatives are available at https://github.com/airbnb/swift#unchecked-sendable."
    severity: error
  no_preconcurrency:
    name: "`@preconcurrency` is discouraged."
    regex: "@preconcurrency"
    match_kinds:
      - attribute.builtin
      - typeidentifier
    message: "Is there a library that supports concurrency instead? We want to be thread safe, if at all possible! Please provide a description if this is unavoidable."
    severity: error
  no_xctest:
    excluded: "(Tests/(VaultBackupTests|VaultFeedTests|VaultiOSTests|VaultSettingsTests)|Sources/TestHelpers)/*"
    name: "XCTest is not allowed in this target."
    regex: "import XCTest"
    match_kinds:
      - keyword
      - identifier
    message: "`import Testing` to use Swift Testing"
    severity: error
