name: Validate PR

on:
  pull_request:
    branches: [main]

env:
  XCODE_VERSION: "15.3"

jobs:
  lint:
    name: Lint
    timeout-minutes: 2
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}
      - name: Lint Sources
        run: make lint
