name: Validate PR

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    timeout-minutes: 2
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Lint Sources
        run: make lint
