name: Validate PR

on:
  pull_request:
    branches: [main]

# env:
#   XCODE_VERSION: "15.3"

jobs:
  lint:
    name: Lint
    timeout-minutes: 2
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Vault

    steps:
      - uses: actions/checkout@v4
      - name: Lint Sources
        run: make lint
